-- Minimal UI translations for nav + toggles. Page content can be added similarly later.

INSERT OR IGNORE INTO ui_translations (namespace, translation_key, lang, text, updated_at) VALUES
-- French
('nav','home','fr','Accueil',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','solutions','fr','Solutions',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','integration_levels','fr','Niveaux d''intégration',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','how_it_works','fr','Méthode',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','use_cases','fr','Cas d''usage',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','about','fr','À propos',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','contact','fr','Contact / Appel',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','language','fr','Langue',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','theme','fr','Thème',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','light','fr','Clair',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','dark','fr','Sombre',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','book_call','fr','Réserver un appel',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','send_message','fr','Envoyer un message',strftime('%Y-%m-%dT%H:%M:%fZ','now')),

-- Spanish
('nav','home','es','Inicio',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','solutions','es','Soluciones',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','integration_levels','es','Niveles de integración',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','how_it_works','es','Cómo funciona',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','use_cases','es','Casos de uso',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','about','es','Acerca de',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','contact','es','Contacto / Llamada',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','language','es','Idioma',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','theme','es','Tema',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','light','es','Claro',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','dark','es','Oscuro',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','book_call','es','Reservar llamada',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','send_message','es','Enviar mensaje',strftime('%Y-%m-%dT%H:%M:%fZ','now')),

-- Portuguese
('nav','home','pt','Início',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','solutions','pt','Soluções',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','integration_levels','pt','Níveis de integração',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','how_it_works','pt','Como funciona',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','use_cases','pt','Casos de uso',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','about','pt','Sobre',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','contact','pt','Contato / Chamada',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','language','pt','Idioma',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','theme','pt','Tema',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','light','pt','Claro',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','dark','pt','Escuro',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','book_call','pt','Agendar chamada',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','send_message','pt','Enviar mensagem',strftime('%Y-%m-%dT%H:%M:%fZ','now')),

-- Arabic
('nav','home','ar','الرئيسية',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','solutions','ar','الحلول',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','integration_levels','ar','مستويات التكامل',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','how_it_works','ar','كيف نعمل',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','use_cases','ar','حالات الاستخدام',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','about','ar','من نحن',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','contact','ar','تواصل / حجز مكالمة',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','language','ar','اللغة',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','theme','ar','المظهر',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','light','ar','فاتح',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','dark','ar','داكن',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','book_call','ar','حجز مكالمة',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','send_message','ar','إرسال رسالة',strftime('%Y-%m-%dT%H:%M:%fZ','now')),

-- Chinese (Mandarin)
('nav','home','zh','首页',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','solutions','zh','解决方案',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','integration_levels','zh','集成级别',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','how_it_works','zh','工作方式',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','use_cases','zh','应用场景',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','about','zh','关于我们',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('nav','contact','zh','联系 / 预约通话',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','language','zh','语言',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','theme','zh','主题',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','light','zh','浅色',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','dark','zh','深色',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','book_call','zh','预约沟通',strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('ui','send_message','zh','发送消息',strftime('%Y-%m-%dT%H:%M:%fZ','now'));
